<template>
  <AdminLayout>
    <div class="space-y-6"><header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-brand-600">Padrón de socios</p><h1 class="mt-1 text-3xl font-semibold text-gray-900">Clientes</h1></div><button class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-600">+ Nuevo Cliente</button></header><section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-theme-xs sm:p-6"><div class="flex flex-col gap-3 lg:flex-row"><input v-model="search" class="h-11 flex-1 rounded-lg border border-gray-200 px-4 text-sm outline-none focus:border-brand-500" placeholder="Buscar por nombre o email..." /><div class="flex flex-wrap gap-2"><button v-for="status in statuses" :key="status" :class="filter === status ? 'bg-brand-500 text-white' : 'bg-gray-50 text-gray-600'" class="rounded-lg px-3 py-2 text-sm font-medium" @click="filter = status">{{ status }}</button></div></div><p class="mt-5 text-sm text-gray-500">{{ filteredMembers.length }} clientes visibles</p><div class="mt-4 overflow-x-auto"><table class="min-w-full"><thead><tr class="border-b border-gray-100 text-start text-xs uppercase tracking-wider text-gray-400"><th class="py-3 text-start">Cliente</th><th class="py-3 text-start">Plan</th><th class="py-3 text-start">Vencimiento</th><th class="py-3 text-start">Estado</th><th class="py-3 text-end">Acción</th></tr></thead><tbody><tr v-for="member in filteredMembers" :key="member.id" class="border-b border-gray-100"><td class="py-4"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-full bg-brand-50 text-xs font-semibold text-brand-600">{{ member.initials }}</span><div><p class="text-sm font-semibold text-gray-800">{{ member.name }}</p><p class="text-xs text-gray-500">{{ member.email }}</p></div></div></td><td class="py-4 text-sm text-gray-600">{{ member.plan }}</td><td class="py-4 text-sm text-gray-600">{{ member.expiry }}</td><td class="py-4"><span :class="badgeClass(member.status)" class="rounded-full px-2.5 py-1 text-xs font-medium">{{ member.status }}</span></td><td class="py-4 text-end"><RouterLink :to="`/clientes/${member.id}`" class="text-sm font-medium text-brand-600">Ver perfil</RouterLink></td></tr></tbody></table></div></section></div>
  </AdminLayout>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
import AdminLayout from '@/components/layout/AdminLayout.vue'
import { useGymData, type MemberStatus } from '@/composables/useGymData'
const { members } = useGymData(); const search = ref(''); const filter = ref('Todos'); const statuses = ['Todos', 'Activo', 'Por vencer', 'Vencido', 'Inactivo']
const filteredMembers = computed(() => members.value.filter((member) => (filter.value === 'Todos' || member.status === filter.value) && `${member.name} ${member.email}`.toLowerCase().includes(search.value.toLowerCase())))
const badgeClass = (status: MemberStatus) => ({ Activo: 'bg-success-50 text-success-600', 'Por vencer': 'bg-warning-50 text-warning-600', Vencido: 'bg-error-50 text-error-600', Inactivo: 'bg-gray-100 text-gray-500' })[status]
</script>
