<template>
  <AdminLayout>
    <div v-if="member" class="space-y-6">
      <button class="flex items-center gap-2 text-sm font-medium text-gray-600" @click="router.push('/clientes')"><span class="flex h-9 w-9 items-center justify-center rounded-full border border-gray-200">←</span> Perfil del Cliente</button>
      <section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs sm:p-8"><div class="flex flex-col gap-5 sm:flex-row sm:items-start"><span class="flex h-20 w-20 items-center justify-center rounded-full bg-blue-light-100 text-2xl font-semibold text-blue-light-600">{{ member.initials }}</span><div class="flex-1"><h1 class="text-3xl font-semibold text-gray-900">{{ member.name }}</h1><p class="mt-1 text-sm text-gray-500">{{ member.email }}</p><span :class="badgeClass(member.status)" class="mt-3 inline-flex rounded-full px-2.5 py-1 text-xs font-medium">{{ member.status }}</span></div></div><div class="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><div class="rounded-xl border border-gray-200 bg-gray-50 p-4"><p class="text-xs text-gray-500">Asistencias</p><p class="mt-1 font-mono text-lg font-semibold text-gray-900">{{ member.attendance.length * 20 + 62 }}</p></div><div class="rounded-xl border border-gray-200 bg-gray-50 p-4"><p class="text-xs text-gray-500">Plan</p><p class="mt-1 text-sm font-semibold text-gray-900">{{ member.plan }}</p></div><div class="rounded-xl border border-gray-200 bg-gray-50 p-4"><p class="text-xs text-gray-500">Miembro desde</p><p class="mt-1 font-mono text-sm font-semibold text-gray-900">{{ member.startDate }}</p></div><div class="rounded-xl border border-gray-200 bg-gray-50 p-4"><p class="text-xs text-gray-500">Vencimiento</p><p class="mt-1 font-mono text-sm font-semibold text-gray-900">{{ member.expiry }}</p></div></div></section>
      <nav class="flex w-fit max-w-full overflow-x-auto rounded-2xl border border-gray-200 bg-white p-1"><button v-for="tabName in tabs" :key="tabName" :class="tab === tabName ? 'bg-white text-gray-900 shadow-theme-sm' : 'text-gray-500'" class="whitespace-nowrap rounded-xl px-5 py-2.5 text-sm font-medium" @click="tab = tabName">{{ tabName }}</button></nav>
      <section v-if="tab === 'Perfil'" class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs"><div class="flex items-center justify-between"><h2 class="text-lg font-semibold text-gray-900">Información Personal</h2><button v-if="!editing" class="rounded-lg border border-gray-200 px-3 py-2 text-sm font-medium text-gray-700" @click="startEditing">Editar</button></div><div v-if="editing" class="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2"><label v-for="field in editableFields" :key="field.key" class="text-xs font-semibold uppercase tracking-wider text-gray-500" :class="field.key === 'address' ? 'sm:col-span-2' : ''">{{ field.label }}<input v-model="editForm[field.key]" :type="field.type" class="mt-2 h-11 w-full rounded-lg border border-gray-200 bg-gray-50 px-3 text-sm" /></label><textarea v-model="editForm.notes" class="sm:col-span-2 rounded-lg border border-gray-200 bg-gray-50 p-3 text-sm" placeholder="Notas internas"></textarea><div class="flex gap-3 sm:col-span-2"><button class="rounded-lg border border-gray-200 px-4 py-2 text-sm" @click="editing = false">Cancelar</button><button class="rounded-lg bg-brand-500 px-4 py-2 text-sm font-medium text-white" @click="saveEditing">Guardar cambios</button></div></div><div v-else class="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2"><InfoField label="Nombre completo" :value="member.name" /><InfoField label="Email" :value="member.email" /><InfoField label="Teléfono" :value="member.phone" /><InfoField label="Fecha de nacimiento" :value="member.birthDate || 'No registrada'" /><InfoField label="Dirección" :value="member.address || 'No registrada'" wide /><InfoField label="Notas" :value="member.notes || 'Sin notas registradas'" wide /></div></section>
      <section v-else-if="tab === 'Suscripción'" class="space-y-5"><div :class="planTheme(member.plan).soft" class="rounded-2xl border p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p :class="planTheme(member.plan).text" class="text-xs font-semibold uppercase">Plan actual</p><h2 class="mt-2 text-2xl font-semibold text-gray-900">{{ member.plan }}</h2><div class="mt-4 grid grid-cols-1 gap-2 text-sm text-gray-600 sm:grid-cols-2"><p v-for="feature in currentPlan?.features || []" :key="feature"><span :class="planTheme(member.plan).text">✓</span> {{ feature }}</p></div></div><p :class="planTheme(member.plan).text" class="text-3xl font-bold">${{ currentPlan?.price.toLocaleString('es-MX') }}</p></div></div><div class="rounded-2xl border border-gray-200 bg-white p-6"><h2 class="font-semibold text-gray-900">Cambiar plan</h2><select class="mt-4 h-11 w-full rounded-lg border border-gray-200 px-3 text-sm sm:max-w-md" :value="member.plan" @change="changePlan"><option v-for="plan in plans" :key="plan.id" :value="plan.name">{{ plan.name }} · ${{ plan.price.toLocaleString('es-MX') }}</option></select></div></section>
      <section v-else-if="tab === 'Asistencia'" class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs"><div class="flex items-center justify-between"><h2 class="text-lg font-semibold text-gray-900">Asistencia últimos 8 semanas</h2><span class="font-mono text-sm font-semibold text-success-600">Total: {{ member.attendance.length * 20 + 62 }} días</span></div><div class="mt-8 flex h-64 items-end justify-between gap-3 border-b border-gray-100 px-4"><div v-for="(height, index) in attendanceBars" :key="index" class="flex flex-1 flex-col items-center gap-2"><div class="w-full max-w-10 rounded-t-lg bg-lime-400" :style="{ height: `${height}%` }"></div><span class="text-xs text-gray-500">S{{ index + 1 }}</span></div></div><div class="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-3"><div class="rounded-xl bg-gray-50 p-4 text-center"><p class="font-semibold text-gray-900">4.1 días</p><p class="text-xs text-gray-500">Promedio semanal</p></div><div class="rounded-xl bg-gray-50 p-4 text-center"><p class="font-semibold text-gray-900">5 días</p><p class="text-xs text-gray-500">Mejor semana</p></div><div class="rounded-xl bg-gray-50 p-4 text-center"><p class="font-semibold text-gray-900">83%</p><p class="text-xs text-gray-500">Tasa de asistencia</p></div></div></section>
      <section v-else-if="tab === 'Entrenador'" class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs"><h2 class="text-lg font-semibold text-gray-900">Entrenador asignado</h2><div v-if="assignedTrainer" class="mt-5 rounded-2xl border border-gray-200 p-5"><div class="flex items-start gap-4"><span class="flex h-14 w-14 items-center justify-center rounded-full bg-blue-light-100 font-semibold text-blue-light-600">{{ assignedTrainer.initials }}</span><div class="flex-1"><h3 class="text-lg font-semibold text-gray-900">{{ assignedTrainer.name }}</h3><p class="text-sm text-success-600">{{ assignedTrainer.specialty }}</p><p class="mt-2 text-sm text-gray-500">{{ assignedTrainer.bio }}</p><p class="mt-3 text-sm text-gray-500">{{ assignedTrainer.schedule }} · ${{ assignedTrainer.rate }} por sesión</p></div><span class="text-orange-500">★ {{ assignedTrainer.rating }}</span></div></div><p v-else class="mt-5 rounded-xl bg-gray-50 p-5 text-sm text-gray-500">Este cliente no tiene un entrenador asignado.</p></section>
      <section v-else class="rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs"><h2 class="text-lg font-semibold text-gray-900">Notas internas</h2><textarea v-model="notes" rows="8" class="mt-5 w-full rounded-xl border border-gray-200 bg-gray-50 p-4 text-sm outline-none focus:border-brand-500"></textarea><button class="mt-5 rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white" @click="saveNotes">✓ Guardar notas</button></section>
    </div><div v-else class="rounded-2xl bg-white p-8 text-center text-gray-500">Cliente no encontrado.</div>
  </AdminLayout>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AdminLayout from '@/components/layout/AdminLayout.vue'
import { useGymData, type MemberStatus } from '@/composables/useGymData'
import InfoField from '@/components/common/InfoField.vue'

const route = useRoute(); const router = useRouter(); const { memberById, updateMember, plans, changeMemberPlan, trainerById } = useGymData(); const member = memberById(String(route.params.id)); const tab = ref('Perfil'); const editing = ref(false); const notes = ref(member?.notes || ''); const tabs = ['Perfil', 'Suscripción', 'Asistencia', 'Entrenador', 'Notas']; const attendanceBars = [48, 72, 58, 74, 58, 48, 74, 58]
const editForm = reactive({ name: member?.name || '', email: member?.email || '', phone: member?.phone || '', address: member?.address || '', birthDate: member?.birthDate || '', notes: member?.notes || '' }); const editableFields = [{ key: 'name', label: 'Nombre completo', type: 'text' }, { key: 'email', label: 'Email', type: 'email' }, { key: 'phone', label: 'Teléfono', type: 'text' }, { key: 'birthDate', label: 'Fecha de nacimiento', type: 'date' }, { key: 'address', label: 'Dirección', type: 'text' }] as const
const currentPlan = computed(() => plans.value.find((plan) => plan.name === member?.plan)); const assignedTrainer = computed(() => member?.trainer ? trainerById(trainersNameToId(member.trainer)) : undefined)
const trainersNameToId = (name: string) => ({ 'Diego Ramírez': 't1', 'Sofía Luna': 't2', 'Andrés Vega': 't3' }[name] || '')
const badgeClass = (status: MemberStatus) => ({ Activo: 'bg-success-50 text-success-600', 'Por vencer': 'bg-warning-50 text-warning-600', Vencido: 'bg-error-50 text-error-600', Inactivo: 'bg-gray-100 text-gray-500' })[status]
const planTheme = (name: string) => { const color = currentPlan.value?.color || plans.value.find((plan) => plan.name === name)?.color; return ({ blue: { text: 'text-blue-light-600', soft: 'bg-blue-light-50 border-blue-light-200' }, lime: { text: 'text-success-600', soft: 'bg-success-50 border-success-200' }, orange: { text: 'text-orange-600', soft: 'bg-orange-50 border-orange-200' }, violet: { text: 'text-purple-600', soft: 'bg-purple-50 border-purple-200' }, red: { text: 'text-error-600', soft: 'bg-error-50 border-error-200' } } as Record<string, { text: string; soft: string }>)[color || ''] || { text: 'text-gray-500', soft: 'bg-gray-50 border-gray-200' } }
const startEditing = () => { editing.value = true }; const saveEditing = () => { if (member) updateMember(member.id, { ...editForm }); editing.value = false }; const saveNotes = () => { if (member) updateMember(member.id, { notes: notes.value }) }; const changePlan = (event: Event) => { const plan = plans.value.find((item) => item.name === (event.target as HTMLSelectElement).value); if (member && plan) changeMemberPlan(member.id, plan) }
</script>
